"""Node: deep_research — 단일 세션으로 심층 리서치 + HTML 리포트 생성.

하이브리드 라우팅:
  - CEO가 deep_research=True로 판단한 리서치 작업만 이 노드로 진입.
  - 단일 도메인: Deep Researcher 1개 → result.html → CEO 스킵, 바로 종료.
  - 다중 도메인: Deep Researcher ×N 병렬 → result_[domain].html × N
                 → CEO가 핵심 요약만 받아 result_whole.html 생성.

기존 멀티 에이전트 파이프라인은 100% 유지 (비리서치 작업).
"""

from __future__ import annotations

import asyncio
import html as html_mod
import re
import time
from datetime import datetime
from pathlib import Path

from langchain_core.messages import AIMessage

from src.config.settings import get_settings
from src.models.messages import DeepResearchResult
from src.prompts.deep_research_prompts import DEEP_RESEARCH_SYSTEM
from src.utils.guards import node_error_handler
from src.utils.logging import get_logger
from src.utils.parallel import run_async
from src.utils.progress import WorkerStatus, get_tracker


def _get_bridge():
    """Get the appropriate bridge based on settings."""
    from src.utils.bridge_factory import get_bridge
    return get_bridge()

logger = get_logger(agent_id="deep_research")


# ── HTML wrapper ─────────────────────────────────

_REPORT_CSS = """\
* { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: 'Apple SD Gothic Neo','Noto Sans KR',-apple-system,sans-serif; font-size: 14px; line-height: 1.7; color: #1a1a1a; background: #f0f2f5; }
.report-wrapper { max-width: 1100px; margin: 0 auto; background: #ffffff; box-shadow: 0 0 40px rgba(0,0,0,0.1); }
.report-header { background: linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%); color: white; padding: 48px 60px 40px; }
.report-header .badge { display: inline-block; background: #FEE500; color: #3C1E1E; font-size: 11px; font-weight: 700; padding: 4px 12px; border-radius: 20px; letter-spacing: 0.5px; margin-bottom: 16px; }
.report-header h1 { font-size: 28px; font-weight: 800; line-height: 1.3; margin-bottom: 8px; }
.report-header .subtitle { font-size: 14px; opacity: 0.7; }
.header-meta { margin-top: 20px; font-size: 13px; opacity: 0.6; border-top: 1px solid rgba(255,255,255,0.2); padding-top: 14px; }
.report-body { padding: 40px 60px; }
.report-footer { background: #1a1a2e; color: rgba(255,255,255,0.6); padding: 18px 60px; font-size: 11px; display: flex; justify-content: space-between; }
.report-footer strong { color: #FEE500; }
@media print {
  body { background: white; font-size: 12px; }
  .report-wrapper { box-shadow: none; max-width: 100%; }
  .report-header { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
  @page { size: A4; margin: 1.5cm; }
}
@media (max-width: 768px) {
  .report-header,.report-footer { padding-left: 24px; padding-right: 24px; }
  .report-body { padding: 24px; }
}"""

_REPORT_THEMES = {
    "deep_research": {
        "badge": "DEEP RESEARCH REPORT",
        "gradient": "linear-gradient(135deg, #1a1a2e 0%, #0f3460 100%)",
        "subtitle": "Enterprise Agent System — Deep Research",
        "footer": "Generated by <strong>Enterprise Agent System</strong> — Deep Research",
    },
    "ceo_synthesis": {
        "badge": "CEO SYNTHESIS REPORT",
        "gradient": "linear-gradient(135deg, #1a2e1a 0%, #0f6034 100%)",
        "subtitle": "Enterprise Agent System — CEO Synthesis",
        "footer": "Generated by <strong>Enterprise Agent System</strong> — CEO Synthesis",
    },
    "domain_analysis": {
        "badge": "DOMAIN ANALYSIS REPORT",
        "gradient": "linear-gradient(135deg, #2e1a1a 0%, #603a0f 100%)",
        "subtitle": "Enterprise Agent System — Domain Analysis",
        "footer": "Generated by <strong>Enterprise Agent System</strong> — Domain Analysis",
    },
}


def _wrap_full_html(
    report_html: str,
    title: str,
    summary: str,
    report_type: str = "deep_research",
) -> str:
    """report_html 본문을 self-contained HTML 페이지로 래핑."""
    from src.utils.report_exporter import _sanitize_report_html
    report_html = _sanitize_report_html(report_html)
    esc_title = html_mod.escape(title)[:100]
    generated_at = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    theme = _REPORT_THEMES.get(report_type, _REPORT_THEMES["deep_research"])

    return (
        f'<!DOCTYPE html>\n<html lang="ko">\n<head>\n'
        f'<meta charset="UTF-8">\n'
        f'<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
        f'<title>{esc_title} - {theme["badge"]}</title>\n'
        f'<style>\n{_REPORT_CSS}\n</style>\n</head>\n<body>\n'
        f'<div class="report-wrapper">\n'
        f'<header class="report-header" style="background:{theme["gradient"]}">\n'
        f'  <div class="badge">{theme["badge"]}</div>\n'
        f'  <h1>{esc_title}</h1>\n'
        f'  <div class="subtitle">{theme["subtitle"]}</div>\n'
        f'  <div class="header-meta">\n'
        f'    <span>작성일 {generated_at}</span>\n'
        f'  </div>\n'
        f'</header>\n'
        f'<div class="report-body">\n  {report_html}\n</div>\n'
        f'<footer class="report-footer">\n'
        f'  <span>{theme["footer"]}</span>\n'
        f'  <span>{generated_at}</span>\n'
        f'</footer>\n'
        f'</div>\n</body>\n</html>'
    )


# ── File I/O ─────────────────────────────────────


def _safe_filename(domain: str) -> str:
    """도메인명을 안전한 파일명으로 변환."""
    safe = re.sub(r'[^\w가-힣-]', '_', domain.strip())[:30]
    return safe.lower() or "unknown"


def _deep_result_to_report(result: DeepResearchResult) -> dict:
    """DeepResearchResult를 export_report용 final_report dict로 변환."""
    findings = []
    for f in result.key_findings:
        if hasattr(f, "model_dump"):
            findings.append(f.model_dump())
        elif isinstance(f, dict):
            findings.append(f)
    return {
        "executive_summary": result.executive_summary,
        "domain_results": [{
            "domain": result.domain,
            "summary": result.executive_summary,
            "quality_score": result.confidence_score,
            "key_deliverables": result.sources[:10] if result.sources else [],
            "gaps": result.gaps if result.gaps else [],
            "file_paths": [],
        }],
        "overall_gap_analysis": ", ".join(result.gaps) if result.gaps else "",
        "recommendations": [],
        "report_html": result.report_html,
    }


def _save_domain_html(result: DeepResearchResult, session_id: str) -> str:
    """result_[domain].html 저장 via export_report. 반환: 저장 경로."""
    from src.utils.report_exporter import export_report
    report_dict = _deep_result_to_report(result)
    domain_session = f"{session_id}/domain_{_safe_filename(result.domain)}"
    output_dir = export_report(
        final_report=report_dict,
        workers=[],
        user_task=result.domain,
        session_id=domain_session,
    )
    if output_dir:
        logger.info("deep_research_html_saved", path=output_dir, domain=result.domain)
        return output_dir
    # Fallback: 직접 저장
    settings = get_settings()
    fallback_dir = Path(settings.report_output_dir) / session_id
    fallback_dir.mkdir(parents=True, exist_ok=True)
    path = fallback_dir / f"result_{_safe_filename(result.domain)}.html"
    full_html = _wrap_full_html(result.report_html, result.domain, result.executive_summary)
    path.write_text(full_html, encoding="utf-8")
    return str(path)


def _save_single_result_html(result: DeepResearchResult, session_id: str) -> str:
    """단일 도메인: results.html 저장 via export_report. 반환: 저장 경로."""
    from src.utils.report_exporter import export_report
    report_dict = _deep_result_to_report(result)
    output_dir = export_report(
        final_report=report_dict,
        workers=[],
        user_task=result.domain,
        session_id=session_id,
    )
    if output_dir:
        logger.info("deep_research_result_saved", path=output_dir)
        return output_dir
    # Fallback: 직접 저장
    settings = get_settings()
    fallback_dir = Path(settings.report_output_dir) / session_id
    fallback_dir.mkdir(parents=True, exist_ok=True)
    path = fallback_dir / "results.html"
    full_html = _wrap_full_html(result.report_html, result.domain, result.executive_summary)
    path.write_text(full_html, encoding="utf-8")
    return str(path)


# ── Single researcher execution ──────────────────


async def _run_single_researcher(
    domain: str,
    user_task: str,
    work_order: str,
    session_id: str,
    progress_callback=None,
    time_budget: float | None = None,
) -> DeepResearchResult:
    """단일 도메인 Deep Research 실행.

    max_turns=200, timeout=40분, effort=high.
    능동적으로 WebSearch/WebFetch/Firecrawl을 반복 사용.
    """
    settings = get_settings()
    bridge = _get_bridge()

    effective_timeout = (
        int(time_budget) if time_budget else settings.deep_research_timeout
    )

    system = DEEP_RESEARCH_SYSTEM.format(
        domain=domain,
        user_task=user_task,
        work_order=work_order,
    )

    result = await bridge.structured_query(
        system_prompt=system,
        user_message=f"리서치 주제: {user_task}\n도메인: {domain}",
        output_schema=DeepResearchResult,
        model=settings.deep_research_model,
        allowed_tools=settings.deep_research_tools,
        timeout=effective_timeout,
        max_turns=settings.deep_research_max_turns,
        effort=settings.deep_research_effort,
        max_tokens=65536,
        progress_callback=progress_callback,
    )
    return result


# ── Reflection ────────────────────────────────────


async def _reflect_on_deep_research(
    result: DeepResearchResult,
    user_task: str,
    domain: str,
    work_order: str,
    session_id: str,
    researcher_elapsed: float,
) -> tuple[DeepResearchResult, str]:
    """Evaluate Deep Research result via Haiku. Returns (final_result, status)."""
    from src.models.messages import ReflectionVerdict
    from src.prompts.reflection_prompts import (
        DEEP_RESEARCH_REFLECTION_SYSTEM, DEEP_RESEARCH_REFLECTION_USER,
    )

    settings = get_settings()
    if not settings.enable_deep_research_reflection:
        return result, "skipped"

    # Sanity check
    sanity_fail = (
        result.confidence_score < 3
        or not result.report_html
        or len(result.report_html) < 200
        or not result.key_findings
    )
    if sanity_fail:
        critique = "Sanity check 실패: 리서치 결과가 비어있거나 극히 부족합니다."
        haiku_elapsed = 0.0
    else:
        # Haiku evaluation
        haiku_start = time.monotonic()
        try:
            bridge = _get_bridge()
            findings_text = "\n".join(
                f"- [{f.category}] {f.content[:200]}" for f in result.key_findings[:10]
            )
            user_msg = DEEP_RESEARCH_REFLECTION_USER.format(
                user_task=user_task,
                executive_summary=result.executive_summary[:1000],
                findings_count=len(result.key_findings),
                findings_text=findings_text,
            )
            verdict = await bridge.structured_query(
                system_prompt=DEEP_RESEARCH_REFLECTION_SYSTEM,
                user_message=user_msg,
                output_schema=ReflectionVerdict,
                model=settings.reflection_model,
                allowed_tools=[],
                timeout=settings.reflection_timeout,
            )
            haiku_elapsed = time.monotonic() - haiku_start
        except Exception as e:
            logger.warning("deep_research_reflection_failed", error=str(e)[:100])
            return result, "pass"

        if verdict.passed:
            return result, "pass"
        critique = verdict.critique

    # Time budget check
    repair_budget = settings.deep_research_timeout - researcher_elapsed - haiku_elapsed
    if repair_budget < settings.reflection_min_repair_budget:
        logger.warning("deep_research_reflection_no_budget", budget=round(repair_budget, 1))
        return result, "fail_kept_original"

    # Repair
    logger.info("deep_research_reflection_repair", domain=domain, critique=critique[:100])
    try:
        repair_work_order = (
            f"{work_order}\n\n"
            f"## 이전 리서치 피드백 (반드시 반영)\n{critique}\n"
            f"이전 결과를 참고하되 지적 사항을 보완하세요."
        )
        repair_result = await _run_single_researcher(
            domain, user_task, repair_work_order, session_id,
            time_budget=repair_budget,
        )
    except Exception as e:
        logger.warning("deep_research_repair_failed", error=str(e)[:100])
        return result, "fail_kept_original"

    # Compare
    repair_better = (
        repair_result.confidence_score >= result.confidence_score
        and len(repair_result.key_findings) >= len(result.key_findings)
        and len(repair_result.report_html) >= len(result.report_html) * 0.8
    )
    if repair_better:
        logger.info("deep_research_repair_adopted", domain=domain)
        return repair_result, "fail_repaired"
    else:
        logger.info("deep_research_repair_rejected", domain=domain)
        return result, "fail_kept_original"


# ── Parallel multi-domain execution ──────────────


async def _run_parallel_researchers(
    domains: list[str],
    user_task: str,
    work_order: str,
    session_id: str,
    tracker=None,
) -> list[DeepResearchResult]:
    """다중 도메인 Deep Research 병렬 실행."""
    settings = get_settings()

    def _make_cb(wid: str):
        def _cb(turn: int, max_t: int) -> None:
            if tracker and max_t > 0:
                tracker.set_real_progress(wid, turn / max_t)
        return _cb

    async def _run_one_with_reflection(d, cb):
        _start = time.monotonic()
        res = await _run_single_researcher(
            d, user_task, work_order, session_id,
            progress_callback=cb,
        )
        elapsed = time.monotonic() - _start
        final, _status = await _reflect_on_deep_research(
            res, user_task, d, work_order, session_id, elapsed,
        )
        return final

    coros = [
        _run_one_with_reflection(
            domain, _make_cb(f"deep_research_{_safe_filename(domain)}"),
        )
        for domain in domains
    ]

    # asyncio.gather with return_exceptions to not lose partial results
    raw_results = await asyncio.gather(*coros, return_exceptions=True)

    results: list[DeepResearchResult] = []
    for domain, raw in zip(domains, raw_results):
        if isinstance(raw, Exception):
            logger.error("deep_research_domain_failed", domain=domain, error=str(raw)[:200])
            # Create a minimal fallback result
            results.append(DeepResearchResult(
                domain=domain,
                executive_summary=f"{domain} 도메인 리서치 실패: {str(raw)[:100]}",
                report_html=f'<div style="padding:20px;color:#c62828;">리서치 실행 실패: {html_mod.escape(str(raw)[:200])}</div>',
                confidence_score=1,
                gaps=[f"리서치 실패: {str(raw)[:100]}"],
            ))
        else:
            results.append(raw)

    return results


# ── Result conversion helpers ────────────────────


def _to_final_report(result: DeepResearchResult, report_path: str) -> dict:
    """DeepResearchResult → CEOFinalReport dict (단일 도메인 직결용)."""
    return {
        "executive_summary": result.executive_summary,
        "domain_results": [{
            "domain": result.domain,
            "summary": result.executive_summary,
            "quality_score": result.confidence_score,
            "key_deliverables": [f.content for f in result.key_findings if f.importance >= 4],
            "gaps": result.gaps,
            "file_paths": [report_path],
        }],
        "overall_gap_analysis": (
            "Deep Research 단일 세션으로 심층 분석 완료."
            if result.confidence_score >= 7
            else f"확신도 {result.confidence_score}/10 — 추가 조사 권장."
        ),
        "recommendations": [],
        "report_html": result.report_html,
    }


def _build_summary_for_ceo(results: list[DeepResearchResult]) -> str:
    """다중 도메인 결과를 CEO 입력으로 생성.

    전체 findings를 importance 순으로 정렬하여 전달.
    CEO가 사용자 지시 맥락에 맞춰 최종 취사선택.
    """
    parts = []
    for r in results:
        parts.append(f"## {r.domain}")
        parts.append(f"요약: {r.executive_summary}")
        parts.append(f"확신도: {r.confidence_score}/10")

        sorted_findings = sorted(r.key_findings, key=lambda f: -f.importance)
        if sorted_findings:
            parts.append("\n수집 데이터 (중요도순):")
            for f in sorted_findings:
                source_tag = f" [{f.source}]" if f.source else ""
                parts.append(f"- [★{f.importance}|{f.category}] {f.content}{source_tag}")

        if r.gaps:
            parts.append(f"\n갭: {', '.join(r.gaps)}")

        if r.sources:
            parts.append(f"\n주요 출처: {', '.join(r.sources[:5])}")

        parts.append("")  # blank line
    return "\n".join(parts)


# ── Main node ────────────────────────────────────


@node_error_handler("deep_research")
def deep_research_node(state: dict) -> dict:
    """Deep Research 메인 노드.

    도메인 수에 따라 분기:
    - 1개: 단일 실행 → result.html → CEO 스킵, 바로 종료
    - N개: 병렬 실행 → result_[domain].html × N → CEO 통합 리포트로 진행
    """
    selected_domains = state.get("selected_domains", [])
    domains = selected_domains if selected_domains else ["research"]
    user_task = state.get("user_task", "")
    work_order = user_task  # work_order removed — use user_task directly
    session_id = state.get("session_id", "unknown")

    # 명확화 Q&A가 있으면 work_order에 합쳐서 컨텍스트 전달
    questions = state.get("clarifying_questions", [])
    answers = state.get("user_answers", [])
    if questions and answers:
        qa_context = "\n".join(
            f"Q: {q}\nA: {a}" for q, a in zip(questions, answers)
        )
        work_order = f"{work_order}\n\n## 사용자 명확화 답변\n{qa_context}"

    if not domains:
        logger.warning("deep_research_no_domains")
        return {"phase": "error", "error_message": "Deep Research: 도메인이 없습니다."}

    # Initialize progress tracker
    tracker = get_tracker(session_id)
    tracker.start([
        (f"deep_research_{_safe_filename(d)}", d) for d in domains
    ])

    messages: list[AIMessage] = []
    start_time = time.monotonic()

    if len(domains) == 1:
        # ── 단일 도메인: 직접 실행 + result.html + CEO 스킵 ──
        domain = domains[0]
        wid = f"deep_research_{_safe_filename(domain)}"
        tracker.update(wid, WorkerStatus.RUNNING, tier=1)

        logger.info("deep_research_single_start", domain=domain)
        try:
            def _progress_cb(turn: int, max_t: int) -> None:
                if max_t > 0:
                    tracker.set_real_progress(wid, turn / max_t)

            async def _run_and_reflect():
                _start = time.monotonic()
                res = await _run_single_researcher(
                    domain, user_task, work_order, session_id,
                    progress_callback=_progress_cb,
                )
                elapsed = time.monotonic() - _start
                return await _reflect_on_deep_research(
                    res, user_task, domain, work_order, session_id, elapsed,
                )

            result, _refl_status = run_async(_run_and_reflect())
            logger.info("deep_research_reflection", domain=domain, status=_refl_status)
            report_path = _save_single_result_html(result, session_id)
            tracker.update(wid, WorkerStatus.DONE, tier=1, summary=result.executive_summary[:50])

            # Emit research_finding events for UI
            if session_id:
                from src.modes.common import emit_mode_event
                for finding in result.key_findings:
                    emit_mode_event(session_id, {
                        "type": "research_finding",
                        "data": {
                            "sub_query": domain,
                            "finding": finding.content,
                            "source": finding.source or "",
                            "depth": 1,
                        },
                    })

            elapsed = time.monotonic() - start_time
            logger.info(
                "deep_research_single_done",
                domain=domain,
                confidence=result.confidence_score,
                elapsed=round(elapsed, 1),
            )

            messages.append(AIMessage(
                content=(
                    f"[Deep Research] {domain} 완료 — "
                    f"확신도 {result.confidence_score}/10, "
                    f"{len(result.key_findings)}개 핵심 발견, "
                    f"{len(result.sources)}개 출처"
                )
            ))

            final_report = _to_final_report(result, report_path)
            tracker.stop()

            return {
                "final_report": final_report,
                "report_file_path": report_path,
                "messages": messages,
                "phase": "complete",
                "deep_research_results": [result.model_dump()],
            }

        except Exception as e:
            tracker.update(wid, WorkerStatus.FAILED, tier=1, summary=str(e)[:50])
            tracker.stop()
            logger.error("deep_research_single_failed", domain=domain, error=str(e)[:200])
            raise

    else:
        # ── 다중 도메인: 병렬 실행 + result_[domain].html × N ──
        for d in domains:
            wid = f"deep_research_{_safe_filename(d)}"
            tracker.update(wid, WorkerStatus.RUNNING, tier=1)

        logger.info("deep_research_multi_start", domains=domains, count=len(domains))

        results = run_async(
            _run_parallel_researchers(domains, user_task, work_order, session_id, tracker=tracker)
        )

        # 각 도메인 HTML 저장
        report_paths = []
        for result in results:
            try:
                path = _save_domain_html(result, session_id)
                report_paths.append(path)
            except Exception as e:
                logger.warning("deep_research_save_failed", domain=result.domain, error=str(e)[:100])

            wid = f"deep_research_{_safe_filename(result.domain)}"
            if result.confidence_score >= 3:
                tracker.update(wid, WorkerStatus.DONE, tier=1, summary=result.executive_summary[:50])
            else:
                tracker.update(wid, WorkerStatus.FAILED, tier=1, summary="low confidence")

            # Emit research_finding events for UI
            if session_id:
                from src.modes.common import emit_mode_event
                for finding in result.key_findings:
                    emit_mode_event(session_id, {
                        "type": "research_finding",
                        "data": {
                            "sub_query": result.domain,
                            "finding": finding.content,
                            "source": finding.source or "",
                            "depth": 1,
                        },
                    })

        elapsed = time.monotonic() - start_time
        logger.info(
            "deep_research_multi_done",
            count=len(results),
            elapsed=round(elapsed, 1),
        )

        for r in results:
            messages.append(AIMessage(
                content=(
                    f"[Deep Research] {r.domain}: "
                    f"확신도 {r.confidence_score}/10, "
                    f"{len(r.key_findings)}개 발견"
                )
            ))

        tracker.stop()

        # CEO 통합 리포트로 진행
        return {
            "deep_research_results": [r.model_dump() for r in results],
            "messages": messages,
            "phase": "ceo_final_report",
        }
